### ISSUE TITLE
German umlauts are not supported

### ISSUE THREAD

**Issue by DirkMahler** [jqassistant-plugin/jqassistant-context-mapper-plugin#2]
I specified a domains containing german umlauts in a context-mapper.cml file and scanned this using the plugin:

```
Domain Mühle {
}

Domain Bäcker {
}
```

The name property of the `:ContextMapper:Domain` node in the database was just `M` instead of `Mühle`, any subsequent domain is not available.

**Comment by StephanPirnbaum** [comment]
This issue is not related to the jQA plugin. When creating a context map with Bounded Contexts as suggested by you with Umlauts, the same effect happens. Most likely it is an issue with the underlying Ecore library. Please raise a ticket for ContextMapper directly.
